---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    image: confluentinc/cp-kafka:5.4.1
    hostname: broker-1
    container_name: broker-1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 'rack1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN_NETWORK:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN_NETWORK://broker-1:29092,LISTENER_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN_NETWORK
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICATION_FACTOR: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_ACKS: 'all'

  broker-2:
    image: confluentinc/cp-kafka:5.4.1
    hostname: broker-2
    container_name: broker-2
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: 'rack1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN_NETWORK:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN_NETWORK://broker-2:29093,LISTENER_HOST://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN_NETWORK
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICATION_FACTOR: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_ACKS: 'all'

  broker-3:
    image: confluentinc/cp-kafka:5.4.1
    hostname: broker-3
    container_name: broker-3
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_RACK: 'rack1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN_NETWORK:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN_NETWORK://broker-3:29094,LISTENER_HOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN_NETWORK
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICATION_FACTOR: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_ACKS: 'all'

  broker-4:
    image: confluentinc/cp-kafka:5.4.1
    hostname: broker-4
    container_name: broker-4
    depends_on:
      - zookeeper
    ports:
      - 9095:9095
      - 29095:29095
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_BROKER_RACK: 'rack2'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN_NETWORK:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN_NETWORK://broker-4:29095,LISTENER_HOST://localhost:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN_NETWORK
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICATION_FACTOR: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_ACKS: 'all'

  broker-5:
    image: confluentinc/cp-kafka:5.4.1
    hostname: broker-5
    container_name: broker-5
    depends_on:
      - zookeeper
    ports:
      - 9096:9096
      - 29096:29096
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_BROKER_RACK: 'rack3'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IN_NETWORK:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IN_NETWORK://broker-5:29096,LISTENER_HOST://localhost:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IN_NETWORK
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICATION_FACTOR: 5
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_ACKS: 'all'

  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.4.1
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - broker-1
      - broker-2
      - broker-3
      - broker-4
      - broker-5
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker-1:29092,broker-2:29093,broker-3:29094,broker-4:29095,broker-5:29096'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"

